[package]
name = "gs-rs"
version = "0.1.0"
authors = [
    "Samuel Valezuela <samuel.valenzuela@tngtech.com>", 
    "Tobias Ramming <tobias.ramming@tngtech.com>",
    "Daniel Pape <daniel.pape@tngtech.com>"
]
edition = "2018"


[dependencies]
log = "0.4.8"
nalgebra = "0.20.0"
approx = "0.3.2"
uuid = "0.8.1"

[dev-dependencies]
env_logger = "0.7.1"
